# Generated by Django 3.2.3 on 2021-06-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='cart.category'),
        ),
        migrations.AlterField(
            model_name='sizevariation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
