# Generated by Django 3.2.3 on 2021-06-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210621_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(default=1, to='cart.SizeVariation'),
        ),
    ]
