# Generated by Django 3.2.3 on 2021-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210621_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(blank=True, to='cart.ColourVariation'),
        ),
    ]
