# Generated by Django 3.2.3 on 2021-06-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='nombre',
        ),
    ]
