# Generated by Django 3.2.3 on 2021-06-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_title_product_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='NOMBRE',
        ),
    ]
