# Generated by Django 3.2.3 on 2021-06-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_nombre_product_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='NOMBRE',
            new_name='nombre',
        ),
    ]
