# Generated by Django 3.2.3 on 2021-06-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_nombre_product_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripcion',
        ),
    ]
