# Generated by Django 3.2.3 on 2021-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_rename_price_product_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
