# Generated by Django 3.2.3 on 2021-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_rename_category_product_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(default='LG', max_length=100),
        ),
    ]
